# Generated by Django 6.0.1 on 2026-04-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidancesessionlog',
            name='ai_synthesis',
            field=models.TextField(blank=True),
        ),
    ]
