# Generated by Django 6.0.1 on 2026-04-26 22:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_userinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('INACCURATE', 'Inaccurate Information'), ('BROKEN_LINK', 'Broken Link'), ('OUTDATED', 'Outdated Requirements'), ('OTHER', 'Other Issue')], default='INACCURATE', max_length=50)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWING', 'Reviewing'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Ignored')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Content Reports',
            },
        ),
    ]
