# Generated by Django 6.0.1 on 2026-04-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_contentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentreport',
            name='report_type',
            field=models.CharField(choices=[('INACCURATE', 'Inaccurate Information'), ('BROKEN_LINK', 'Broken Link'), ('OTHER', 'Other Issue')], default='INACCURATE', max_length=50),
        ),
    ]
