# Generated by Django 6.0.1 on 2026-04-26 22:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_contentreport_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('combination', models.CharField(blank=True, max_length=255)),
                ('interests', models.TextField(blank=True)),
                ('personality', models.JSONField(blank=True, default=dict)),
                ('ai_synthesis', models.TextField(blank=True)),
                ('matches_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
