# Generated by Django 6.0.1 on 2026-04-26 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_studentlead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentlead',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Student Leads'},
        ),
    ]
