# Generated by Django 6.0.1 on 2026-05-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_alter_studentlead_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidancesessionlog',
            name='raw_interests',
            field=models.TextField(blank=True, help_text='The raw text the student typed about their interests.'),
        ),
    ]
