# Generated by Django 6.0.1 on 2026-05-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_guidancesessionlog_raw_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidancesessionlog',
            name='feedback_comment',
            field=models.TextField(blank=True, help_text='Optional feedback comment from the user'),
        ),
        migrations.AddField(
            model_name='guidancesessionlog',
            name='rating',
            field=models.IntegerField(blank=True, help_text='User rating (1-5)', null=True),
        ),
    ]
