# Generated by Django 6.0.1 on 2026-05-18 23:47

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_guidancesessionlog_feedback_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('programme_a_id', models.UUIDField()),
                ('programme_b_id', models.UUIDField()),
                ('same_university', models.BooleanField(default=False)),
                ('rating', models.IntegerField(blank=True, help_text='Student rating 1–5', null=True)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Comparison Logs',
            },
        ),
    ]
