# Generated by Django 6.0.1 on 2026-04-03 19:14

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('award_level', models.CharField(default='Bachelor', help_text='e.g. Bachelor Degree, Diploma', max_length=100)),
                ('duration_months', models.IntegerField(default=0)),
                ('qualification_framework', models.CharField(blank=True, help_text='e.g. UQF 10', max_length=50)),
                ('study_mode', models.CharField(blank=True, help_text='e.g. Full Time', max_length=50)),
                ('duration_years', models.FloatField(default=3)),
                ('description', models.TextField(blank=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('head_office', models.CharField(blank=True, max_length=255)),
                ('university_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('accreditation_status', models.CharField(blank=True, max_length=255)),
                ('registration_no', models.CharField(blank=True, max_length=100)),
                ('overview', models.TextField(blank=True, help_text='AI-generated high-level overview.')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('semester', models.IntegerField(help_text='Semester number (1-8)')),
                ('year', models.IntegerField(default=1, help_text='Year of study (e.g. 1, 2, 3)')),
                ('credits', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='universities.programme')),
            ],
        ),
        migrations.CreateModel(
            name='CareerOutlook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Job title or Career path', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_outlooks', to='universities.programme')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='General description of requirements')),
                ('min_points', models.FloatField(default=0.0, help_text='Minimum points required')),
                ('required_subjects', models.TextField(blank=True, help_text='Comma-separated list of required subjects (e.g. Physics, Math)')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('programme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_requirement', to='universities.programme')),
            ],
        ),
        migrations.AddField(
            model_name='programme',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='universities.university'),
        ),
    ]
