# Generated by Django 6.0.1 on 2026-02-01 17:23

import django.db.models.deletion
from pgvector.django import VectorExtension
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('degree_level', models.CharField(choices=[('BACHELOR', 'Bachelor Degree'), ('DIPLOMA', 'Diploma'), ('CERTIFICATE', 'Certificate'), ('MASTER', 'Master Degree'), ('PHD', 'PhD')], default='BACHELOR', max_length=20)),
                ('duration_years', models.IntegerField(default=3)),
                ('description', models.TextField(blank=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('semester', models.IntegerField(help_text='Semester number (1-8)')),
                ('credits', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='universities.programme')),
            ],
        ),
        migrations.CreateModel(
            name='CareerOutlook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title or Career path', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_outlooks', to='universities.programme')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='General description of requirements')),
                ('min_points', models.FloatField(default=0.0, help_text='Minimum points required')),
                ('required_subjects', models.TextField(blank=True, help_text='Comma-separated list of required subjects (e.g. Physics, Math)')),
                ('programme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_requirement', to='universities.programme')),
            ],
        ),
        migrations.AddField(
            model_name='programme',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='universities.university'),
        ),
    ]
