# Generated by Django 6.0.1 on 2026-02-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='code',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='name',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='university',
        ),
        migrations.AddField(
            model_name='programme',
            name='award_level',
            field=models.CharField(default='Bachelor', help_text='e.g. Bachelor Degree, Diploma', max_length=100),
        ),
        migrations.AddField(
            model_name='programme',
            name='duration_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='programme',
            name='qualification_framework',
            field=models.CharField(blank=True, help_text='e.g. UQF 10', max_length=50),
        ),
        migrations.AddField(
            model_name='programme',
            name='study_mode',
            field=models.CharField(blank=True, help_text='e.g. Full Time', max_length=50),
        ),
        migrations.AlterField(
            model_name='programme',
            name='degree_level',
            field=models.CharField(blank=True, default='BACHELOR', max_length=50),
        ),
        migrations.AlterField(
            model_name='programme',
            name='duration_years',
            field=models.FloatField(default=3),
        ),
    ]
