# Generated by Django 6.0.1 on 2026-04-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='career_outlooks',
            field=models.JSONField(blank=True, default=list, help_text='List of extracted career objects'),
        ),
        migrations.DeleteModel(
            name='CareerOutlook',
        ),
    ]
