# Generated by Django 6.0.1 on 2026-02-01 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_remove_programme_code_remove_programme_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='universities.university'),
        ),
    ]
