# Generated by Django 6.0.1 on 2026-04-03 23:22

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_programme_career_outlooks_delete_careeroutlook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionrequirement',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
