# Generated by Django 6.0.1 on 2026-02-01 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_programme_name_programme_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='degree_level',
        ),
    ]
