# Generated by Django 6.0.1 on 2026-04-14 04:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_alter_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('combination', models.CharField(blank=True, max_length=100)),
                ('interests', models.TextField(blank=True)),
                ('personality_data', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
