# Generated by Django 6.0.1 on 2026-02-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_remove_programme_degree_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='accreditation_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='university',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='university',
            name='head_office',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='university',
            name='registration_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='university_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
