# Generated by Django 6.0.1 on 2026-02-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_university_accreditation_status_university_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='overview',
            field=models.TextField(blank=True, help_text='AI-generated high-level overview.'),
        ),
    ]
