# Generated by Django 6.0.1 on 2026-04-25 23:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_studentlead'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAdmissionRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(default='2025/2026', max_length=50)),
                ('general_requirements', models.JSONField(blank=True, default=dict)),
                ('admission_cycles', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Programme Categories',
            },
        ),
        migrations.AddField(
            model_name='admissionrequirement',
            name='accepts_out_foundation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionrequirement',
            name='admission_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionrequirement',
            name='alevel_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='admissionrequirement',
            name='diploma_fields_accepted',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='admissionrequirement',
            name='min_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionrequirement',
            name='min_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admissionrequirement',
            name='olevel_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='admissionrequirement',
            name='out_foundation_min_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionrequirement',
            name='pathway',
            field=models.CharField(choices=[('ACSEE', 'ACSEE'), ('DIPLOMA', 'DIPLOMA'), ('OTHER', 'OTHER')], default='ACSEE', max_length=50),
        ),
        migrations.AddField(
            model_name='programme',
            name='academic_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='degree_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='is_campus_college',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='location_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='ownership',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='parent_institution_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_colleges', to='universities.university'),
        ),
        migrations.AddField(
            model_name='university',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='po_box',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='tcu_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admissionrequirement',
            name='description',
            field=models.TextField(blank=True, help_text='General description of requirements or raw requirements text'),
        ),
        migrations.AlterField(
            model_name='admissionrequirement',
            name='min_points',
            field=models.FloatField(blank=True, default=0.0, help_text='Minimum points required', null=True),
        ),
        migrations.AlterField(
            model_name='admissionrequirement',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_requirements', to='universities.programme'),
        ),
        migrations.AlterField(
            model_name='admissionrequirement',
            name='required_subjects',
            field=models.TextField(blank=True, help_text='Legacy string'),
        ),
        migrations.AlterField(
            model_name='university',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmes', to='universities.programmecategory'),
        ),
    ]
