# Generated by Django 6.0.1 on 2026-02-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_university_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=1, help_text='Year of study (e.g. 1, 2, 3)'),
        ),
    ]
