# Generated by Django 6.0.1 on 2026-04-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_globaladmissionrequirement_programmecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='rank',
            field=models.IntegerField(default=100),
        ),
    ]
