# Generated by Django 6.0.1 on 2026-04-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_university_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='is_stem',
            field=models.BooleanField(default=False, help_text='Whether this is a Science, Tech, Engineering, or Math course'),
        ),
        migrations.AlterField(
            model_name='university',
            name='rank',
            field=models.IntegerField(default=100, help_text='Global/Local rank for dashboard prioritization'),
        ),
    ]
