# Generated by Django 6.0.1 on 2026-02-03 04:18

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0008_backfill_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
