# Generated by Django 6.0.1 on 2026-05-18 23:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0008_programme_is_stem_alter_university_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('programme_a_id', models.UUIDField(db_index=True)),
                ('programme_b_id', models.UUIDField(db_index=True)),
                ('result', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('programme_a_id', 'programme_b_id')},
            },
        ),
    ]
